apiVersion: v1
kind: Service
metadata:
  name: job-processor-service
spec:
  selector:
    app: coding-challenge
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  type: LoadBalancer