apiVersion: apps/v1
kind: Deployment
metadata:
  name: job-processor-deployment
  labels:
    app: coding-challenge
spec:
  replicas: 2
  selector:
    matchLabels:
      app: coding-challenge
  template:
    metadata:
      labels:
        app: coding-challenge
    spec:
      containers:
        - name: coding-challenge
          image: coding-challenge:latest
          ports:
            - containerPort: 8080
          resources:
            requests:
              cpu: 500m
